# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 284a8a3339cb4f75124e568a6c56a134fce38693c5c64e8393338f6b7ba04793b146c30a7fad95910d8749a6fa87d9f123982df7f8cbfee8c8d633ca12767dab

test:
  secret_key_base: f6728704d9c2e2e0a6342a70c8d2ca3ae411a87cb6e7ae66708a8fb89d6732e444eb6dc4486f6f7caeb101605f15f780a5aa45f5280052d108d5b87e3fab8ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
